package finalproject.suppliersystem.supplier.criticalityview.repository;

import finalproject.suppliersystem.supplier.criticalityview.view.SupplierProductCategoryCriticalityView;
import org.springframework.data.jpa.repository.JpaRepository;

public interface ISupplierProductCategoryCriticalityViewRepository extends JpaRepository<SupplierProductCategoryCriticalityView, Long>
{
}
